/**
 * Pure rendering logic for chat bubbles. Both the persisted message view
 * and the in-flight streaming view convert their state into the same
 * RenderBlock[] shape; the chat page's `renderBlocks` snippet draws them
 * identically. Keeping this logic out of the Svelte component lets us
 * pin the contract in vitest — chat rendering is core enough that a
 * silent regression here breaks every conversation.
 */

import type { ChatMessage, MessagePart, ModelEntry } from './types/api';

/**
 * The model-name label to show above an assistant bubble. Defaults to the
 * conversation's label, but when a message was generated by a model OTHER
 * than the conversation's stored default — a per-turn override, or a kept
 * multi-model fan-out branch — labels it by that model so each sibling reads
 * truthfully.
 *
 * Falling back to the conversation label for the default model is what
 * preserves custom-preset naming: a preset's `modelUsed` equals the
 * conversation's stored base model id, so it doesn't get rewritten to the
 * bare base-model name. An unknown model (endpoint since removed from config)
 * degrades to its `endpoint::owner/model` id with the prefixes stripped.
 */
export function assistantLabelForMessage(
	m: Pick<ChatMessage, 'role' | 'modelUsed'>,
	conversationModelId: string,
	conversationLabel: string,
	models: readonly ModelEntry[],
): string {
	if (m.role !== 'assistant' || !m.modelUsed || m.modelUsed === conversationModelId) {
		return conversationLabel;
	}
	const found = models.find((x) => x.id === m.modelUsed);
	if (found) return found.displayName;
	const afterEndpoint = m.modelUsed.includes('::')
		? m.modelUsed.slice(m.modelUsed.indexOf('::') + 2)
		: m.modelUsed;
	const slash = afterEndpoint.lastIndexOf('/');
	return slash >= 0 ? afterEndpoint.slice(slash + 1) : afterEndpoint;
}

// --- block shape --------------------------------------------------------
//
// One element of the per-bubble render. The snippet branches on `type`
// and draws each block — no logic lives in the markup. New content
// types (web_search outputs, MCP results, memory recalls…) land here as
// a new union variant and both render paths get them for free.

export type RenderBlock =
	/** `open` means the `<details>` element should render expanded —
	 *  in-flight reasoning starts expanded (so the user watches the
	 *  model think); persisted reasoning starts collapsed (the user
	 *  already saw it while it streamed; now it's metadata). */
	| { type: 'reasoning'; text: string; open: boolean }
	/** Pre-rendered markdown HTML — server-side shiki for persisted
	 *  assistant rows, client-side markdown-it for live streaming.
	 *  Both pass through markdown-it with html=false so {@html} is safe. */
	| { type: 'html'; html: string }
	/** Plain-text fallback for messages without rendered HTML (user
	 *  rows, just-arrived in-flight text whose rAF render hasn't fired). */
	| { type: 'plain-text'; text: string }
	| {
			type: 'tool_call';
			toolCallId: string;
			toolName: string;
			arguments: string;
			/** Pre-rendered code-fenced HTML when the tool's primary
			 *  argument is source code (today: run_python). Renderer
			 *  prefers this over JSON pretty-print when present. */
			argsHtml?: string;
			result?: string;
			isError?: boolean;
			status: 'executing' | 'done' | 'error' | 'pending_approval';
			/** Media the tool produced — rendered inside the tool block
			 *  under the result so the chip / preview lives where the
			 *  tool call lives, not in a separate visible bubble. */
			attachments?: ToolResultAttachment[];
	  }
	| { type: 'image'; mediaId: string; alt?: string }
	| { type: 'video'; mediaId: string }
	/** Non-image, non-video media attachment (xlsx/csv/pdf/json/...) —
	 *  rendered as a download chip rather than inline. Filename + size
	 *  are denormalized off the media row at persist time so the
	 *  renderer needs no lookup; the download link still points at
	 *  /api/media/{id}/content. */
	| { type: 'file'; mediaId: string; filename: string; byteSize: number };

// --- in-flight segments -------------------------------------------------
//
// The live streaming state for the in-flight bubble is a single ordered
// list of segments — text and tool_call interleaved in arrival order.
// This is what makes multi-tool-per-turn render correctly: text₀ →
// tool_a → text₁ → tool_b → text₂ produces 5 segments; the renderer
// just walks them in order.

export interface InFlightTextSegment {
	kind: 'text';
	text: string;
	/** Cached rendered HTML — populated by the page's rAF effect. Empty
	 *  string means "render plain-text fallback while waiting." */
	html: string;
	/** The text value `html` was produced from. Lets the rAF effect skip
	 *  the markdown render for segments whose text didn't change since
	 *  the last tick — when a multi-segment turn (text → tool → text)
	 *  has only one segment growing, the others would otherwise be
	 *  re-parsed for nothing on every frame. Optional so tests can
	 *  construct segments without it; the rAF effect treats missing as
	 *  "needs render." */
	htmlFromText?: string;
}

export interface InFlightToolCallSegment {
	kind: 'tool_call';
	toolCallId: string;
	toolName: string;
	arguments: string;
	status: 'executing' | 'done' | 'error' | 'pending_approval';
	result?: string;
	isError?: boolean;
}

export interface InFlightReasoningSegment {
	kind: 'reasoning';
	text: string;
}

export type InFlightSegment =
	| InFlightTextSegment
	| InFlightToolCallSegment
	| InFlightReasoningSegment;

// --- in-flight segment transformations ---------------------------------
//
// Pure (current segments, event) → new segments. The chat page calls
// these on each SSE event and assigns the result back to the $state. By
// keeping the transformations pure we can vitest the state machine
// without spinning up a Svelte component or mocking $state.

/** Append a text chunk. Grows the trailing text segment when one exists,
 *  otherwise opens a new segment (which happens after every tool_call). */
export function appendText(segments: InFlightSegment[], chunk: string): InFlightSegment[] {
	if (segments.length === 0) {
		return [{ kind: 'text', text: chunk, html: '' }];
	}
	const last = segments[segments.length - 1];
	if (last.kind === 'text') {
		return [...segments.slice(0, -1), { kind: 'text', text: last.text + chunk, html: last.html }];
	}
	return [...segments, { kind: 'text', text: chunk, html: '' }];
}

/** Append a reasoning chunk. Same grow-or-open pattern as appendText —
 *  consecutive reasoning chunks coalesce into one segment, but if a
 *  text or tool_call lands in between (the model interleaved), a new
 *  reasoning segment opens for the next batch. This is what lets the
 *  in-flight bubble render reasoning at its chronological position
 *  rather than always at the top. */
export function appendReasoning(segments: InFlightSegment[], chunk: string): InFlightSegment[] {
	if (segments.length === 0) {
		return [{ kind: 'reasoning', text: chunk }];
	}
	const last = segments[segments.length - 1];
	if (last.kind === 'reasoning') {
		return [...segments.slice(0, -1), { kind: 'reasoning', text: last.text + chunk }];
	}
	return [...segments, { kind: 'reasoning', text: chunk }];
}

/** Push a new tool_call segment in 'executing' state. Subsequent
 *  updateToolCallArgs/updateToolCallResult calls find it by id. */
export function pushToolCall(
	segments: InFlightSegment[],
	toolCallId: string,
	toolName: string,
): InFlightSegment[] {
	return [
		...segments,
		{ kind: 'tool_call', toolCallId, toolName, arguments: '', status: 'executing' },
	];
}

/** Append a chunk to a tool_call's `arguments` string, identified by
 *  toolCallId. No-ops when the id isn't found (defensive against an
 *  args_delta arriving before its own start event, which would be a
 *  spec-violating upstream but we don't crash). */
export function updateToolCallArgs(
	segments: InFlightSegment[],
	toolCallId: string,
	argsDelta: string,
): InFlightSegment[] {
	const idx = segments.findIndex((s) => s.kind === 'tool_call' && s.toolCallId === toolCallId);
	if (idx < 0) return segments;
	const seg = segments[idx];
	if (seg.kind !== 'tool_call') return segments;
	return [
		...segments.slice(0, idx),
		{ ...seg, arguments: seg.arguments + argsDelta },
		...segments.slice(idx + 1),
	];
}

/** Mark a tool_call as finished — flips status to 'done' or 'error' and
 *  records the result. */
export function updateToolCallResult(
	segments: InFlightSegment[],
	toolCallId: string,
	result: string,
	isError: boolean,
): InFlightSegment[] {
	const idx = segments.findIndex((s) => s.kind === 'tool_call' && s.toolCallId === toolCallId);
	if (idx < 0) return segments;
	const seg = segments[idx];
	if (seg.kind !== 'tool_call') return segments;
	return [
		...segments.slice(0, idx),
		{ ...seg, status: isError ? 'error' : 'done', result, isError },
		...segments.slice(idx + 1),
	];
}

/** Flip a tool_call segment to `pending_approval` so the in-flight bubble
 *  renders the Allow / Allow Always / Reject buttons the instant the
 *  server-side decision lands — instead of waiting for the post-stream
 *  invalidate to surface the persisted status. */
export function markToolCallPendingApproval(
	segments: InFlightSegment[],
	toolCallId: string,
	toolName: string,
	args: string,
): InFlightSegment[] {
	const idx = segments.findIndex((s) => s.kind === 'tool_call' && s.toolCallId === toolCallId);
	if (idx < 0) {
		// Defensive — server emitted pending_approval for a tool_call we
		// never saw a `tool_call_start` for. Synthesize the segment so
		// the UI doesn't drop the approval prompt entirely.
		return [
			...segments,
			{
				kind: 'tool_call',
				toolCallId,
				toolName,
				arguments: args,
				status: 'pending_approval',
			},
		];
	}
	const seg = segments[idx];
	if (seg.kind !== 'tool_call') return segments;
	return [
		...segments.slice(0, idx),
		{ ...seg, status: 'pending_approval', arguments: args || seg.arguments },
		...segments.slice(idx + 1),
	];
}

// --- conversion: messages / segments → render blocks --------------------

/** Convert a persisted ChatMessage into RenderBlock[] for the unified
 *  renderer. tool_call parts get their status from `toolResults` — when
 *  a matching tool_result exists in the side-map, status is 'done' (or
 *  'error' if isError); otherwise it's 'executing' (still in-flight). */
export function messageToBlocks(
	m: ChatMessage,
	toolResults: Map<string, ToolResultEntry>,
): RenderBlock[] {
	const blocks: RenderBlock[] = [];
	if (m.reasoningText) blocks.push({ type: 'reasoning', text: m.reasoningText, open: false });

	// Use the server-rendered contentHtml at the position of the FIRST
	// text part. This preserves shiki's code-block formatting which we
	// can't reproduce client-side (shiki stays server-only by bundle).
	let usedContentHtml = false;
	for (const p of m.parts) {
		const block = partToBlock(p, m, toolResults, usedContentHtml);
		if (!block) continue;
		if (block.type === 'html' && p.type === 'text') usedContentHtml = true;
		blocks.push(block);
	}
	return blocks;
}

function partToBlock(
	p: MessagePart,
	m: ChatMessage,
	toolResults: Map<string, ToolResultEntry>,
	usedContentHtml: boolean,
): RenderBlock | null {
	switch (p.type) {
		case 'text':
			if (!p.text) return null;
			if (!usedContentHtml && m.role === 'assistant' && m.contentHtml) {
				return { type: 'html', html: m.contentHtml };
			}
			return { type: 'plain-text', text: p.text };
		case 'tool_call': {
			const entry = toolResults.get(p.toolCallId);
			let status: 'executing' | 'done' | 'error' | 'pending_approval';
			if (!entry) status = 'executing';
			else if (entry.status === 'pending_approval') status = 'pending_approval';
			else status = entry.isError ? 'error' : 'done';
			return {
				type: 'tool_call',
				toolCallId: p.toolCallId,
				toolName: p.toolName,
				arguments: p.arguments,
				...(p.argsHtml ? { argsHtml: p.argsHtml } : {}),
				result: entry?.result,
				isError: entry?.isError,
				status,
				...(entry?.attachments ? { attachments: entry.attachments } : {}),
			};
		}
		case 'image':
			return { type: 'image', mediaId: p.mediaId, alt: p.alt };
		case 'video':
			return { type: 'video', mediaId: p.mediaId };
		case 'file':
			return {
				type: 'file',
				mediaId: p.mediaId,
				filename: p.filename,
				byteSize: p.byteSize,
			};
		case 'reasoning':
			// reasoning parts (future): folded into the message-level
			// reasoning block at the top, not re-rendered inline
			return null;
		case 'tool_result':
			// tool_result parts live on role:'tool' messages — folded into
			// matching tool_call blocks via the toolResults map
			return null;
	}
}

/** Convert in-flight streaming state into RenderBlock[]. Segments
 *  render in arrival order — reasoning, text, and tool_calls all
 *  interleave at whatever position they streamed in at. This is what
 *  matches the user's mental model: "things should appear in the
 *  order they happened, not get reordered after the fact." */
export function inFlightToBlocks(segments: InFlightSegment[]): RenderBlock[] {
	const blocks: RenderBlock[] = [];
	for (const seg of segments) {
		switch (seg.kind) {
			case 'reasoning':
				// open: true for live reasoning — the user is actively
				// watching the model think. The persisted side (after
				// invalidate) shows the same content collapsed.
				blocks.push({ type: 'reasoning', text: seg.text, open: true });
				break;
			case 'text':
				if (seg.html) blocks.push({ type: 'html', html: seg.html });
				else if (seg.text) blocks.push({ type: 'plain-text', text: seg.text });
				break;
			case 'tool_call':
				blocks.push({
					type: 'tool_call',
					toolCallId: seg.toolCallId,
					toolName: seg.toolName,
					arguments: seg.arguments,
					result: seg.result,
					isError: seg.isError,
					status: seg.status,
				});
				break;
		}
	}
	return blocks;
}

// --- visibility / tool-result indexing ----------------------------------

/** Strip role:'tool' messages from the visible list. Their results are
 *  folded into the assistant message that emitted the matching
 *  tool_call (see `buildToolResultsMap` for the lookup). */
export function filterVisibleMessages(messages: ChatMessage[]): ChatMessage[] {
	return messages.filter((m) => m.role !== 'tool');
}

/** Media attachments the tool produced during execution (e.g. files
 *  Python wrote under /workspace/). Carried through the tool-result
 *  index so the inline tool block can render them as chips / inline
 *  previews where the tool_call sits, instead of needing a separate
 *  visible bubble for the tool message itself. */
export type ToolResultAttachment =
	| { type: 'image'; mediaId: string }
	| { type: 'video'; mediaId: string }
	| { type: 'file'; mediaId: string; filename: string; byteSize: number };

export interface ToolResultEntry {
	result: string;
	isError: boolean;
	status?: 'pending_approval';
	/** Optional; absent when the tool didn't produce any media. */
	attachments?: ToolResultAttachment[];
}

/** Build the `toolCallId → result` lookup that messageToBlocks uses to
 *  resolve tool_call statuses. Carries the pending_approval status
 *  through so the inline tool block can render the Allow / Always /
 *  Reject prompt right where its tool_call appears. Also collects any
 *  image / video / file parts that share the tool message — those are
 *  the media the tool produced, surfaced under the tool block. */
export function buildToolResultsMap(messages: ChatMessage[]): Map<string, ToolResultEntry> {
	const out = new Map<string, ToolResultEntry>();
	for (const msg of messages) {
		if (msg.role !== 'tool') continue;
		let resultPart: Extract<MessagePart, { type: 'tool_result' }> | null = null;
		const attachments: ToolResultAttachment[] = [];
		for (const p of msg.parts) {
			if (p.type === 'tool_result') resultPart = p;
			else if (p.type === 'image') attachments.push({ type: 'image', mediaId: p.mediaId });
			else if (p.type === 'video') attachments.push({ type: 'video', mediaId: p.mediaId });
			else if (p.type === 'file') {
				attachments.push({
					type: 'file',
					mediaId: p.mediaId,
					filename: p.filename,
					byteSize: p.byteSize,
				});
			}
		}
		if (!resultPart) continue;
		const entry: ToolResultEntry = {
			result: resultPart.result,
			isError: resultPart.isError === true,
		};
		if (resultPart.status === 'pending_approval') entry.status = 'pending_approval';
		if (attachments.length > 0) entry.attachments = attachments;
		out.set(resultPart.toolCallId, entry);
	}
	return out;
}

/**
 * Find every persisted tool_result row on the visible branch with
 * `status: 'pending_approval'` and return its toolCallId. Returned in
 * branch order so the UI renders prompts in the same sequence the
 * model proposed them. The inline ToolCallBlock already has the
 * tool name + args from the assistant message's tool_call part via
 * messageToBlocks — the page-level pending list only needs ids for
 * the "all decided?" effect and the resume POST body.
 *
 * Returns [] in the steady state — pending appears only when the
 * model tried to use an MCP tool the user hasn't trusted yet AND
 * the relay halted so the user could decide.
 */
export function buildPendingApprovals(messages: ChatMessage[]): string[] {
	const out: string[] = [];
	for (const msg of messages) {
		if (msg.role !== 'tool') continue;
		for (const p of msg.parts) {
			if (p.type !== 'tool_result') continue;
			if (p.status !== 'pending_approval') continue;
			out.push(p.toolCallId);
		}
	}
	return out;
}

export interface RenderedConversation {
	visibleMessages: ChatMessage[];
	toolResultsByCallId: Map<string, ToolResultEntry>;
	pendingApprovals: string[];
}

/**
 * Single-pass derivation of the three view-model pieces the chat page
 * recomputes on every messages update. The three independent passes —
 * filterVisibleMessages, buildToolResultsMap, buildPendingApprovals —
 * each walked the array on its own, so a mid-stream tool result update
 * cost three array walks where one would do.
 */
export function buildRenderedConversation(messages: ChatMessage[]): RenderedConversation {
	const visibleMessages: ChatMessage[] = [];
	const toolResultsByCallId = new Map<string, ToolResultEntry>();
	const pendingApprovals: string[] = [];
	for (const msg of messages) {
		if (msg.role !== 'tool') {
			visibleMessages.push(msg);
			continue;
		}
		let resultPart: Extract<MessagePart, { type: 'tool_result' }> | null = null;
		const attachments: ToolResultAttachment[] = [];
		for (const p of msg.parts) {
			if (p.type === 'tool_result') {
				resultPart = p;
				if (p.status === 'pending_approval') pendingApprovals.push(p.toolCallId);
			} else if (p.type === 'image') attachments.push({ type: 'image', mediaId: p.mediaId });
			else if (p.type === 'video') attachments.push({ type: 'video', mediaId: p.mediaId });
			else if (p.type === 'file') {
				attachments.push({
					type: 'file',
					mediaId: p.mediaId,
					filename: p.filename,
					byteSize: p.byteSize,
				});
			}
		}
		if (!resultPart) continue;
		const entry: ToolResultEntry = {
			result: resultPart.result,
			isError: resultPart.isError === true,
		};
		if (resultPart.status === 'pending_approval') entry.status = 'pending_approval';
		if (attachments.length > 0) entry.attachments = attachments;
		toolResultsByCallId.set(resultPart.toolCallId, entry);
	}
	return { visibleMessages, toolResultsByCallId, pendingApprovals };
}

// --- bubble-merge flags -------------------------------------------------

/** Compute whether the message at `index` in `visibleMessages` should
 *  visually merge with the previous or next message (so a multi-iteration
 *  tool turn's separate assistant rows render as one continuous bubble).
 *
 *  Merges happen only between consecutive `role:'assistant'` rows.
 *  Editing breaks the merge — the inline-edit replaces the article
 *  entirely, so we don't want it visually fused with its neighbors.
 *
 *  `mergeIntoInFlight` is true when the in-flight bubble is open and the
 *  message at `index` is the trailing assistant message — the live
 *  bubble is then conceptually a continuation of that row (the
 *  approval-resume case, where the prior turn halted on a tool call and
 *  the resumed turn streams in the next iteration's text). Forcing
 *  `mergeWithNext` here keeps the bottom rounded corner off so the
 *  live bubble visually fuses with the prior one, matching how the
 *  persisted view will look after invalidate. Avoids the "snap from
 *  two bubbles to one" jolt when the stream completes. */
export function computeMergeFlags(
	visibleMessages: ChatMessage[],
	index: number,
	editingMessageId: string | null,
	mergeIntoInFlight = false,
): { mergeWithPrev: boolean; mergeWithNext: boolean } {
	const m = visibleMessages[index];
	if (!m || m.role !== 'assistant' || m.id === editingMessageId) {
		return { mergeWithPrev: false, mergeWithNext: false };
	}
	const prev = index > 0 ? visibleMessages[index - 1] : null;
	const next = index < visibleMessages.length - 1 ? visibleMessages[index + 1] : null;
	const isLastVisible = index === visibleMessages.length - 1;
	return {
		mergeWithPrev: !!prev && prev.role === 'assistant' && prev.id !== editingMessageId,
		mergeWithNext:
			(!!next && next.role === 'assistant' && next.id !== editingMessageId) ||
			(mergeIntoInFlight && isLastVisible),
	};
}

// --- code-shaped tool args ---------------------------------------------------
//
// Some tools' "args" are really source code wrapped in a JSON envelope
// (today: `run_python`, whose only parameter `code` is a multi-line
// Python string). Rendering that envelope verbatim — `{"code":"import
// pandas\\nimport numpy ..."}` — is technically accurate but unreadable
// at a glance. The streaming relay's `maybeRenderCodeArg` (server-only)
// pre-renders the code through shiki at end-of-turn so the persisted
// view shows syntax-highlighted Python. The streaming view doesn't get
// shiki (it would blow the client bundle), but it CAN still show the
// code as multi-line monospace text instead of the JSON envelope — that's
// what `extractCodeArg` is for. Both paths consult the same
// CODE_ARG_TOOLS table so the client and server agree on which tools
// have code-shaped args and which language to highlight as.

export interface CodeArgMeta {
	codeField: string;
	language: string;
}

export const CODE_ARG_TOOLS: Record<string, CodeArgMeta> = {
	run_python: { codeField: 'code', language: 'python' },
};

/**
 * Pull out the source-code field of a code-shaped tool's args, tolerating
 * partial / mid-stream JSON. Returns null when the tool isn't in
 * CODE_ARG_TOOLS, the args don't yet contain the code field, or the
 * value is empty.
 *
 * Strategy:
 *  1. Try strict JSON.parse first. Works for any complete message and
 *     for the persisted-message path.
 *  2. Fall back to a small state machine that walks the input looking
 *     for `"<field>":` then captures the following JSON string,
 *     decoding standard escapes (`\n`, `\t`, `\r`, `\"`, `\\`, `\/`,
 *     `\b`, `\f`, `\uXXXX`) as it goes. On unterminated input it
 *     returns what it has — which is exactly the right behavior for
 *     mid-stream rendering: every additional token makes the displayed
 *     code grow until the closing `"` flips us into the steady state.
 *
 * Unknown escapes pass through verbatim so a malformed model output
 * doesn't make the args panel go blank.
 */
export function extractCodeArg(
	toolName: string,
	rawArgs: string,
): { code: string; language: string } | null {
	const meta = CODE_ARG_TOOLS[toolName];
	if (!meta || !rawArgs) return null;

	try {
		const parsed = JSON.parse(rawArgs);
		if (parsed && typeof parsed === 'object') {
			const code = (parsed as Record<string, unknown>)[meta.codeField];
			if (typeof code === 'string' && code.length > 0) {
				return { code, language: meta.language };
			}
		}
		return null;
	} catch {
		// Fall through to partial-extract.
	}

	const code = partialExtractStringField(rawArgs, meta.codeField);
	if (code === null || code.length === 0) return null;
	return { code, language: meta.language };
}

/**
 * Skill activation tools (`activate_skill` / `read_skill_file`) render with a
 * bespoke compact affordance instead of the generic tool envelope — like
 * run_python, dispatched purely on the tool name (the only signal the client
 * has). This parses the name/path out of the args and UNWRAPS the result
 * (`<skill_content>` / `<skill_file>` envelope, `<skill_resources>` manifest)
 * so the UI can show the instructions/file directly, no XML/JSON plumbing.
 */
export interface SkillToolDisplay {
	kind: 'activate' | 'read_file';
	/** Skill name from the args (may be null mid-stream before args land). */
	skillName: string | null;
	/** Bundle-relative path (read_skill_file only). */
	path: string | null;
	/** Unwrapped body — markdown instructions (activate) or file text
	 *  (read_file) — or null while the call is still executing (no result),
	 *  or the error message when the call failed. */
	body: string | null;
	/** Bundled-resource paths surfaced by activate_skill, if any. */
	resources: string[];
	isError: boolean;
}

function extractStringField(rawArgs: string, field: string): string | null {
	if (!rawArgs) return null;
	try {
		const parsed = JSON.parse(rawArgs);
		if (parsed && typeof parsed === 'object') {
			const v = (parsed as Record<string, unknown>)[field];
			if (typeof v === 'string' && v.length > 0) return v;
		}
	} catch {
		// mid-stream / malformed — fall through to the tolerant scan.
	}
	const partial = partialExtractStringField(rawArgs, field);
	return partial && partial.length > 0 ? partial : null;
}

/** Pull the inner content of a `<tag …>…</tag>` envelope, or null. */
function unwrapTag(s: string, tag: string): string | null {
	const m = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`).exec(s);
	return m ? m[1].trim() : null;
}

/** Split a `<skill_resources>… - path …</skill_resources>` manifest out of the
 *  body, returning the body sans-manifest plus the listed resource paths. */
function splitSkillResources(s: string): { text: string; resources: string[] } {
	const block = /<skill_resources>([\s\S]*?)<\/skill_resources>/.exec(s);
	if (!block) return { text: s.trim(), resources: [] };
	const resources = block[1]
		.split('\n')
		.map((l) => l.trim())
		.filter((l) => l.startsWith('- '))
		.map((l) => l.slice(2).trim())
		.filter(Boolean);
	const text = s.replace(block[0], '').trim();
	return { text, resources };
}

export function parseSkillToolDisplay(
	toolName: string,
	rawArgs: string,
	result: string | undefined,
	isError: boolean,
): SkillToolDisplay | null {
	if (toolName !== 'activate_skill' && toolName !== 'read_skill_file') return null;
	const kind: SkillToolDisplay['kind'] = toolName === 'activate_skill' ? 'activate' : 'read_file';
	const skillName = extractStringField(rawArgs, 'name');
	const path = kind === 'read_file' ? extractStringField(rawArgs, 'path') : null;

	let body: string | null = null;
	let resources: string[] = [];
	if (result !== undefined && result !== '') {
		if (isError) {
			// Recoverable tool errors come back as {"error":"…"}.
			try {
				const parsed = JSON.parse(result);
				body =
					parsed && typeof parsed === 'object' && typeof parsed.error === 'string'
						? parsed.error
						: result;
			} catch {
				body = result;
			}
		} else if (kind === 'activate') {
			const inner = unwrapTag(result, 'skill_content') ?? result;
			const split = splitSkillResources(inner);
			body = split.text;
			resources = split.resources;
		} else {
			body = unwrapTag(result, 'skill_file') ?? result;
		}
	}
	return { kind, skillName, path, body, resources, isError };
}

function partialExtractStringField(args: string, field: string): string | null {
	const key = `"${field}"`;
	let i = args.indexOf(key);
	if (i < 0) return null;
	i += key.length;
	// Skip whitespace + colon + whitespace
	while (i < args.length && (args[i] === ' ' || args[i] === '\t' || args[i] === '\n')) i++;
	if (args[i] !== ':') return null;
	i++;
	while (i < args.length && (args[i] === ' ' || args[i] === '\t' || args[i] === '\n')) i++;
	if (args[i] !== '"') return null;
	i++;

	let out = '';
	while (i < args.length) {
		const c = args[i];
		if (c === '\\') {
			const next = args[i + 1];
			if (next === undefined) break; // incomplete escape at end-of-stream
			if (next === 'n') out += '\n';
			else if (next === 't') out += '\t';
			else if (next === 'r') out += '\r';
			else if (next === '"') out += '"';
			else if (next === '\\') out += '\\';
			else if (next === '/') out += '/';
			else if (next === 'b') out += '\b';
			else if (next === 'f') out += '\f';
			else if (next === 'u') {
				if (i + 5 >= args.length) break;
				const hex = args.slice(i + 2, i + 6);
				if (!/^[0-9a-fA-F]{4}$/.test(hex)) {
					// Malformed unicode escape — pass through to avoid a blank panel.
					out += '\\u' + hex;
				} else {
					out += String.fromCharCode(parseInt(hex, 16));
				}
				i += 6;
				continue;
			} else {
				// Unknown escape — pass the next char through so we don't
				// lose data on a malformed token.
				out += next;
			}
			i += 2;
		} else if (c === '"') {
			return out;
		} else {
			out += c;
			i++;
		}
	}
	return out;
}
