/**
 * File round-trip helpers for the code interpreter.
 *
 *   collectConversationFiles → pulls user-uploaded files and Python-
 *     generated files from the conversation's active branch and packages
 *     them as `RunPythonPreFile`s the worker mounts into `/workspace/`.
 *
 *   persistGeneratedFiles → takes the worker's post-call new/modified
 *     files, stores their bytes via MediaStore, and registers them as
 *     `origin: 'generated'` rows with `sourceModel: 'run_python'`.
 *     Returns the media ids so the streaming relay can `linkMessageMedia`
 *     them to the persisted tool row.
 *
 * Filter rule for materialization (in collectConversationFiles): we
 * deliberately skip media generated by image / video models even when
 * they're on the conversation's active branch. Those are outputs, not
 * analysis input; the model that wrote them can't read Python anyway,
 * and dumping image bytes into Pyodide's VFS just inflates the worker
 * payload. The included set is:
 *
 *   - `origin: 'uploaded'` of any kind (xlsx, csv, pdf, txt, image to
 *     analyze with PIL, ...) — the user explicitly attached it
 *   - `origin: 'generated' AND sourceModel: 'run_python'` of any kind
 *     (an earlier Python turn's output that the next turn might
 *     reference) — round-trip continuity for the iterating-on-a-file
 *     use case the v1 plan optimizes for
 */

import { createHash } from 'node:crypto';
import { extname } from 'node:path';
import { and, eq, inArray } from 'drizzle-orm';
import { getDb } from '../db/client';
import { media, messageMedia } from '../db/schema';
import { walkActiveBranch } from '../db/queries/messages';
import { insertMedia, type MediaKind } from '../db/queries/media';
import { getMediaStore } from '../media/disk-store';
import type { RunPythonPreFile, RunPythonPostFile } from './pool';

/**
 * Returns the conversation's attached + Python-generated files, packaged
 * for materialization into `/workspace/`. Filenames are deduped — if two
 * uploads share the same filename, the most recently created one wins
 * (which is the natural "latest version" interpretation).
 */
export async function collectConversationFiles(
	conversationId: string,
	userId: string,
): Promise<RunPythonPreFile[]> {
	const db = getDb();
	const branch = walkActiveBranch(conversationId);
	if (branch.length === 0) return [];
	const messageIds = branch.map((m) => m.id);

	// JOIN message_media × media, filter on ownership + the include rule.
	// We can't use the includes-everything `listMediaForUser` because it
	// scans by user; here the natural scoping is "this conversation",
	// which the join expresses directly.
	const rows = db
		.select({
			mediaId: media.id,
			storagePath: media.storagePath,
			originalFilename: media.originalFilename,
			contentType: media.contentType,
			origin: media.origin,
			sourceModel: media.sourceModel,
			createdAt: media.createdAt,
		})
		.from(messageMedia)
		.innerJoin(media, eq(media.id, messageMedia.mediaId))
		.where(
			and(
				inArray(messageMedia.messageId, messageIds),
				eq(media.userId, userId),
				// Don't include hard-deleted rows — the file is gone.
				// `isNull` on hardDeletedAt would normally do this, but
				// for round-trip purposes the simpler check works since
				// hard-deleted rows have null storagePath only after a
				// later cleanup pass; for in-flight tool calls the row
				// state is "live until proven otherwise" and we tolerate
				// the rare "file moved out from under us" by surfacing
				// the read failure as a per-file skip below.
			),
		)
		.all();

	// Apply the include rule: uploaded OR (generated AND sourceModel='run_python').
	const eligible = rows.filter(
		(r) => r.origin === 'uploaded' || (r.origin === 'generated' && r.sourceModel === 'run_python'),
	);

	// Newest-first per filename. The map collapses duplicates.
	eligible.sort((a, b) => b.createdAt - a.createdAt);
	const byFilename = new Map<string, (typeof eligible)[number]>();
	for (const r of eligible) {
		const name = r.originalFilename ?? `${r.mediaId}${extname(r.contentType) || ''}`;
		if (!byFilename.has(name)) byFilename.set(name, r);
	}

	const store = getMediaStore();
	const out: RunPythonPreFile[] = [];
	for (const [filename, r] of byFilename) {
		try {
			const result = await store.open(r.storagePath, r.contentType);
			if (!result) continue;
			const chunks: Buffer[] = [];
			for await (const chunk of result.stream) {
				chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
			}
			const bytes = Buffer.concat(chunks);
			const u8 = new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
			out.push({
				filename,
				bytes: u8,
				sha256: createHash('sha256').update(u8).digest('hex'),
			});
		} catch {
			// File missing or unreadable (race with hard-delete / disk
			// cleanup, transient I/O error). Skip rather than failing the
			// whole call — the model sees the file as absent in /workspace/
			// and can adjust.
		}
	}
	return out;
}

/**
 * Persist files Python wrote under `/workspace/` as conversation media.
 * Returns the new media ids so the relay can link them to the freshly-
 * persisted tool-result row.
 */
export async function persistGeneratedFiles({
	userId,
	files,
}: {
	userId: string;
	files: readonly RunPythonPostFile[];
}): Promise<string[]> {
	if (files.length === 0) return [];

	const store = getMediaStore();
	const ids: string[] = [];
	for (const f of files) {
		const contentType = guessContentType(f.filename);
		const kind: MediaKind = contentType.startsWith('image/')
			? 'image'
			: contentType.startsWith('video/')
				? 'video'
				: 'file';
		const buf = Buffer.from(f.bytes);
		const ref = await store.put({ bytes: buf, contentType, kind });
		const { id } = insertMedia({
			userId,
			storagePath: ref.storagePath,
			contentType: ref.contentType,
			byteSize: ref.byteSize,
			kind,
			sourceEndpointId: null,
			sourceModel: 'run_python',
			promptExcerpt: null,
			origin: 'generated',
			originalFilename: f.filename,
		});
		ids.push(id);
	}
	return ids;
}

// --- content-type guessing ------------------------------------------------

const CONTENT_TYPE_BY_EXT: Record<string, string> = {
	'.png': 'image/png',
	'.jpg': 'image/jpeg',
	'.jpeg': 'image/jpeg',
	'.gif': 'image/gif',
	'.webp': 'image/webp',
	'.avif': 'image/avif',
	'.svg': 'image/svg+xml',
	'.mp4': 'video/mp4',
	'.webm': 'video/webm',
	'.mov': 'video/quicktime',
	'.txt': 'text/plain',
	'.md': 'text/markdown',
	'.csv': 'text/csv',
	'.json': 'application/json',
	'.pdf': 'application/pdf',
	'.zip': 'application/zip',
	'.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	'.xls': 'application/vnd.ms-excel',
	'.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	'.doc': 'application/msword',
	'.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
	'.ppt': 'application/vnd.ms-powerpoint',
	'.html': 'text/html',
	'.htm': 'text/html',
	'.xml': 'application/xml',
};

function guessContentType(filename: string): string {
	const ext = extname(filename).toLowerCase();
	return CONTENT_TYPE_BY_EXT[ext] ?? 'application/octet-stream';
}
