import sveltejs from '@sveltejs/eslint-config';
import { defineConfig } from 'eslint/config';
import svelteParser from 'svelte-eslint-parser';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

/**
 * Shared by the `.ts` and `.svelte` blocks below. `projectService` is what
 * gives the type-aware rules a TS program per file.
 */
const parserOptions = {
	extraFileExtensions: ['.svelte'],
	svelteConfig,
	projectService: {
		// Compiler options for the allowDefaultProject files below; without it
		// they get an inferred project with no node types (process.env -> any).
		defaultProject: 'tsconfig.node.json',
		// Files with no owning tsconfig: these four config files, and
		// `service-worker.ts`, which SvelteKit deliberately excludes from the
		// app program (different globals/lib). `scripts/` gets its own tsconfig
		// instead — see scripts/tsconfig.json. `vite.config.ts` is NOT listed:
		// SvelteKit's generated tsconfig already includes it, and a file may
		// not be in both.
		allowDefaultProject: [
			'drizzle.config.ts',
			'playwright.config.ts',
			'vitest.config.ts',
			'vitest.eval.config.ts',
			'src/service-worker.ts',
		],
	},
};

export default defineConfig([
	{
		ignores: [
			'build/',
			'.svelte-kit/',
			'coverage/',
			'drizzle/',
			'playwright-report/',
			'static/',
			'test-results/',
			// esbuild output, regenerated by `pnpm build:worker`.
			'src/lib/server/code-interpreter/worker.js',
		],
	},

	// The Svelte team's shared config: eslint + typescript-eslint
	// `recommended` + eslint-plugin-svelte, with prettier's formatting rules
	// switched off. The `**/*.{ts,svelte}` block below layers the full
	// `recommendedTypeChecked` on top of it.
	sveltejs,

	{
		languageOptions: {
			globals: {
				// Injected by vite's `define` (see vite.config.ts); typed in
				// app.d.ts, but `no-undef` doesn't read type declarations.
				__APP_VERSION__: 'readonly',
			},
		},
	},

	{
		files: ['**/*.{ts,svelte}'],
		extends: [ts.configs.recommendedTypeChecked],
		languageOptions: { parserOptions },
		rules: {
			// `checksVoidReturn` is off: every hit was an async callback handed
			// to an event/timer API that ignores the return value
			// (`setInterval`, `parentPort.on`, `process.on('sveltekit:shutdown')`),
			// each already catching internally. The checks that stay on are the
			// ones that catch real bugs — a bare Promise used as a condition
			// (`if (maybeAsync())`, always truthy) or spread.
			'@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: false }],
			// Off: the rule doesn't understand *contractual* async. Nearly every
			// one of the 213 hits is a function that MUST return a promise to
			// satisfy a type it's assigned to, but whose body happens not to
			// await — `const r: MediaUrlResolver = async (id) => …` where the
			// type is `(id: string) => Promise<string>`, `vi.fn(async () => new
			// Response(…))` standing in for `fetch`, `startStreamingRelay()`
			// declaring `Promise<ReadableStream>`. Dropping `async` at those
			// sites is a type error, so the rule can only be satisfied by
			// contorting the code it flags.
			'@typescript-eslint/require-await': 'off',
		},
	},

	{
		rules: {
			// The shared config sets `argsIgnorePattern` only, but the codebase
			// uses the `_name` discard convention for destructured bindings too
			// (`const { trustedMcpTools: _excluded, ...rest }`).
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					args: 'after-used',
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_',
				},
			],
			// Disagrees with the actual compiler: it called three
			// `a11y_click_events_have_key_events` ignores unused, and deleting
			// them made svelte-check warn again. `pnpm check` is the authority
			// on which svelte-ignores are live, so don't let lint contradict it.
			'svelte/no-unused-svelte-ignore': 'off',
			// A quoted attribute can't carry `\n` — `{'a\nb'}` and "a\nb" are
			// different strings, so a mustache holding escapes isn't useless.
			'svelte/no-useless-mustaches': ['error', { ignoreStringEscape: true }],
			// The shared config enables this with no options, so it fires on
			// `import { x }` + `import type { X }` from one module — a split we
			// use deliberately. `allowSeparateTypeImports` exempts exactly that
			// pair, so keep the rule on: two *value* imports from one module is
			// still worth catching.
			'no-duplicate-imports': ['error', { allowSeparateTypeImports: true }],
			// Wants every `<a href>` and `goto()` wrapped in `resolve()`, which
			// only matters under a non-empty `paths.base`. We don't set one.
			'svelte/no-navigation-without-resolve': 'off',
			// Flags every `new Map()`/`new Set()` in a component. Ours are
			// either locals built fresh inside a `$derived.by` (already
			// reactive via the deriving) or deliberately non-reactive
			// bookkeeping — see the `#loadedPages` comment in gallery-feed.
			// The places that need reactivity already use SvelteMap.
			'svelte/prefer-svelte-reactivity': 'off',
		},
	},

	// Plain-JS config and fixture files are in no TS program, so the
	// type-aware rules can't run on them.
	{
		files: ['**/*.{js,mjs,cjs}'],
		extends: [ts.configs.disableTypeChecked],
	},

	{
		files: ['tests/**/*.ts'],
		rules: {
			// `expect(obj.method)` hands the reference to a matcher that only
			// inspects it — it is never invoked, so there is no `this` to lose.
			// The rule can't see that; it's the documented false positive with
			// jest/vitest-style assertions. Still on for src/.
			'@typescript-eslint/unbound-method': 'off',
			// In test doubles an assertion often exists to shape INFERENCE, not
			// to change the expression's own type — `vi.fn(() => null as unknown)`
			// widens the mock's return type so a later call can hand it an
			// object. The rule judges the expression in isolation and calls that
			// redundant. Deleting what it flags is NOT safe: when this exemption
			// landed, doing so broke `pnpm check` with 50 errors across 11 files.
			// The flagged count tracks how much typing `tests/` carries and grows
			// with it, so re-measure rather than trusting a number here:
			//   eslint 'tests/**/*.ts' --rule \
			//     '{"@typescript-eslint/no-unnecessary-type-assertion":"error"}'
			// `pnpm check` is the authority, same as with svelte-ignore. Still on
			// for src/.
			'@typescript-eslint/no-unnecessary-type-assertion': 'off',
		},
	},

	// MUST stay after the `recommendedTypeChecked` block. That preset's base
	// config sets `languageOptions.parser` to the TS parser for every file it
	// matches, which clobbers the Svelte parser and makes every `.svelte` file
	// fail to parse ("Type expected" on the markup). Re-assert it here:
	// svelte-eslint-parser for the file, TS for the `<script lang="ts">` block.
	{
		files: ['**/*.svelte'],
		languageOptions: {
			parser: svelteParser,
			parserOptions: { ...parserOptions, parser: ts.parser },
		},
		rules: {
			// Svelte 5 requires `let` for the `$props()` destructure; props are
			// reassignable from the parent. ESLint sees bindings that are never
			// written locally and asks for `const`, which doesn't compile.
			'prefer-const': 'off',
		},
	},
]);
