import sveltejs from '@sveltejs/eslint-config';
import { defineConfig } from 'eslint/config';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

export default defineConfig([
	{
		ignores: [
			'build/',
			'.svelte-kit/',
			'coverage/',
			'drizzle/',
			'playwright-report/',
			'static/',
			'test-results/',
			// esbuild output, regenerated by `pnpm build:worker`.
			'src/lib/server/code-interpreter/worker.js',
		],
	},

	// The Svelte team's shared config: eslint + typescript-eslint
	// `recommended` (deliberately NOT `recommendedTypeChecked`) +
	// eslint-plugin-svelte, with prettier's formatting rules switched off.
	sveltejs,

	{
		languageOptions: {
			globals: {
				// Injected by vite's `define` (see vite.config.ts); typed in
				// app.d.ts, but `no-undef` doesn't read type declarations.
				__APP_VERSION__: 'readonly',
			},
		},
	},

	{
		files: ['**/*.{ts,svelte}'],
		languageOptions: {
			parserOptions: {
				parser: ts.parser,
				extraFileExtensions: ['.svelte'],
				svelteConfig,
				projectService: {
					// Files with no owning tsconfig: these four config files, and
					// `service-worker.ts`, which SvelteKit deliberately excludes
					// from the app program (different globals/lib). `scripts/`
					// gets its own tsconfig instead — see scripts/tsconfig.json.
					// `vite.config.ts` is NOT listed: SvelteKit's generated
					// tsconfig already includes it, and a file may not be in both.
					allowDefaultProject: [
						'drizzle.config.ts',
						'playwright.config.ts',
						'vitest.config.ts',
						'vitest.eval.config.ts',
						'src/service-worker.ts',
					],
				},
			},
		},
		rules: {
			// Type-aware rules added back on top of the non-type-checked base.
			// Deliberately a short list: these four catch real defects (a
			// dropped promise, an async callback passed where a void return is
			// expected). The rest of `recommendedTypeChecked` is ~900
			// `no-unsafe-*` reports on the untyped upstream/JSON boundary plus
			// 246 `only-throw-error` on SvelteKit's own `throw error(401)` /
			// `throw redirect(302)` idiom, which is not fixable.
			'@typescript-eslint/await-thenable': 'error',
			'@typescript-eslint/no-base-to-string': 'error',
			'@typescript-eslint/no-floating-promises': 'error',
			// `checksVoidReturn` is off: every hit was an async callback handed
			// to an event/timer API that ignores the return value
			// (`setInterval`, `parentPort.on`, `process.on('sveltekit:shutdown')`),
			// each already catching internally. The checks that stay on are the
			// ones that catch real bugs — a bare Promise used as a condition
			// (`if (maybeAsync())`, always truthy) or spread.
			'@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: false }],
		},
	},

	{
		rules: {
			// The shared config sets `argsIgnorePattern` only, but the codebase
			// uses the `_name` discard convention for destructured bindings too
			// (`const { trustedMcpTools: _excluded, ...rest }`).
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					args: 'after-used',
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_',
				},
			],
			// Disagrees with the actual compiler: it called three
			// `a11y_click_events_have_key_events` ignores unused, and deleting
			// them made svelte-check warn again. `pnpm check` is the authority
			// on which svelte-ignores are live, so don't let lint contradict it.
			'svelte/no-unused-svelte-ignore': 'off',
			// A quoted attribute can't carry `\n` — `{'a\nb'}` and "a\nb" are
			// different strings, so a mustache holding escapes isn't useless.
			'svelte/no-useless-mustaches': ['error', { ignoreStringEscape: true }],
			// Fires on `import { x }` + `import type { X }` from one module.
			// The core rule predates `import type` and can't tell them apart.
			'no-duplicate-imports': 'off',
			// Wants every `<a href>` and `goto()` wrapped in `resolve()`, which
			// only matters under a non-empty `paths.base`. We don't set one.
			'svelte/no-navigation-without-resolve': 'off',
			// Flags every `new Map()`/`new Set()` in a component. Ours are
			// either locals built fresh inside a `$derived.by` (already
			// reactive via the deriving) or deliberately non-reactive
			// bookkeeping — see the `#loadedPages` comment in gallery-feed.
			// The places that need reactivity already use SvelteMap.
			'svelte/prefer-svelte-reactivity': 'off',
		},
	},

	// Plain-JS config and fixture files are in no TS program, so the
	// type-aware rules can't run on them.
	{
		files: ['**/*.{js,mjs,cjs}'],
		extends: [ts.configs.disableTypeChecked],
	},

	{
		files: ['**/*.svelte'],
		rules: {
			// Svelte 5 requires `let` for the `$props()` destructure; props are
			// reassignable from the parent. ESLint sees bindings that are never
			// written locally and asks for `const`, which doesn't compile.
			'prefer-const': 'off',
		},
	},
]);
