/**
 * `virtual:pwa-register` is generated by vite-plugin-pwa, which only runs in
 * vite.config.ts — so under vitest the specifier doesn't resolve at all, and
 * Vite fails the whole module at import-analysis time rather than at the
 * dynamic import. That kills any test that renders the root layout, even
 * though the layout guards the import with `import.meta.env.PROD` and never
 * reaches it. Hence a stub, not a `vi.mock`: the mock runs too late.
 *
 * Registering nothing is the honest stand-in — a test that wants the SW
 * lifecycle wants a real browser, not this. The options bag is accepted and
 * discarded rather than omitted, so the shape matches the `registerSW({
 * immediate, onNeedRefresh, onRegisteredSW })` call it stands in for.
 */
export function registerSW(_options?: unknown): (reloadPage?: boolean) => Promise<void> {
	return async () => {};
}
